name: CI

on:
  push:
    branches: [main, develop]

jobs:
#  build:
#    name: Build Docker image
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Build pipeline-spark image
#        run: docker compose build

  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check . --exit-zero

  dbt:
    name: Validate dbt models
    runs-on: ubuntu-latest
    env:
      DB_USERNAME: ci
      DB_PASSWORD: ci
      DB_HOST: ci
      DB_PORT: "5432"
      DB_NAME: ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dbt
        run: pip install dbt-postgres

      - name: Run dbt parse
        run: dbt parse --project-dir dbt/ --profiles-dir dbt/